### ISSUE TITLE
Add badges for public scan services: SSLLabs, etc.

### ISSUE THREAD

**Issue by rugk** [PrivateBin/Directory#1]
E.g. like this:

```
![Status](https://img.shields.io/website/https/bin.snopyta.org.svg)
![Security Headers](https://img.shields.io/security-headers?url=https%3A%2F%2Fbin.snopyta.org)
![Mozilla Observatory](https://img.shields.io/mozilla-observatory/grade/bin.snopyta.org.svg)
```

![Status](https://img.shields.io/website/https/bin.snopyta.org.svg)
![Security Headers](https://img.shields.io/security-headers?url=https%3A%2F%2Fbin.snopyta.org)
![Mozilla Observatory](https://img.shields.io/mozilla-observatory/grade/bin.snopyta.org.svg)

(some seem to be mistakenly catched by GitHub/broken)

and maybe add SSLLabs if https://github.com/badges/shields/issues/4845 is granted or we find a different badge.

Of course, you could also directly access the API and embed the result in a nicer way than a badge – the point is the information provided that gives an initial security evaluation.

**Comment by elrido** [comment]
Been pondering this. The website status would overlap with planned status checks, which is the next item on my list.

The badges represent meaningful information, but I don't like that this leaks information to a third party site, plus its bound to be slow when, for example, 30 times 3 badges get loaded visiting the page.

I would feel more comfortable to offer a button-styled link to take the visitors to the test sites to look up the results for instances they consider using. Not so practical UI, but better for their privacy.

Implementing these checks for our selves is probably to time consuming in maintenance to keep up with security recommendations. But if you know of key HTTP headers to check, I do have these available in the response, when checking the servers, and can generate some score or status check flags based on this. Checking the TLS protocol is a lot more tricky in the library that I used, though.

**Comment by rugk** [comment]
…or you do it how GitHub does and cache the resulting images locally on the server. This also solves the loading issue.

About self-checking:
Nah, don't implement _the whole thing_ by ourselves, that is surely not possible/realistic. But just call the respective APIs from the server, i.e. SSLLabs API, HTTP etc. See the actual [shields.io repo](https://github.com/badges/shields), they also just do that.

Having another look I actually see shields.io itself [offers an API](https://shields.io/endpoint). Thus, if you call this on the server, you get a JSON can can just evaluate that.

IMHO the last way is the best one, it's easy to do, all big maintenance effort is "outsourced" to a third-party and you get up-to-date results with a simple JSON request.

**Comment by elrido** [comment]
I looked at the API, but if I understand it correctly it's to inject custom content into a shield and return that to your users instead, not to query their stored information, sorry.

How about we just add a column "Tools" that contains links to an instances results on SSLabs, SecurityHeaders, Mozilla Observatory, etc. in the interim?

**Comment by rugk** [comment]
> I looked at the API, but if I understand it correctly it's to inject custom content into a shield and return that to your users instead, not to query their stored information,

Uff, you're right. Okay, I've asked here for that: https://github.com/badges/shields/issues/4846

So only workable way for now would be to query the third-party APIs by ourselves.

**Comment by rugk** [comment]
Ohh and here we have a solution:
https://github.com/badges/shields/issues/4846#issuecomment-606634821

E.g.
https://img.shields.io/security-headers.json?url=https%3A%2F%2Fbin.snopyta.org -> JSON

**Comment by elrido** [comment]
Looking a bit deeper into this: mozilla observatory and security headers check the same things, but the observatory seems more comprehensive. Their API docs at https://github.com/mozilla/http-observatory/blob/master/httpobs/docs/api.md

SSLLabs API has rather problematic [terms](https://github.com/mozilla/http-observatory/issues/119#issuecomment-244736759). We would have to inform users that by adding a site, they agree to SSLLabs terms and conditions and display or link these on that page. For using their name in that section, we would also have to ask for permission to do so. And for using the API on a public website (which this is), we again have to ask for their permission.

I'll implement the mozilla observatory API directly, but for SSLLabs I would at most add a link where visitors can check for themselves - their conditions on the API use seem too restrictive for me to go through the effort of implementing it, only to have to remove it again at their whim. I hope you understand.
