### ISSUE TITLE
Docker build COPY failed

### ISSUE THREAD

**Issue by didnt1able** [PrivateBin/Directory#11]
```
Step 15/16 : COPY target/x86_64-unknown-linux-musl/release/directory /bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder619333042/target/x86_64-unknown-linux-musl/release/directory: no such file or directory
```
Any help would be appreciated.

**Comment by elrido** [comment]
Is this with the standalone dockerfile or the one used by the Makefile? If the former, does your docker version support multistage builds, if the latter, maybe check the permissions of the file?

I assume that you want to build the application yourself and the [published image on the hub](https://hub.docker.com/r/privatebin/directory/) that is built vie the docker cloud is of no use to you.

**Comment by didnt1able** [comment]
This is with building from the dockerfile. Permissions are okay.  My docker version is 19.03.6 which supports multistage builds

**Comment by elrido** [comment]
I was assuming you did a docker build using https://github.com/PrivateBin/Directory/blob/master/Dockerfile.standalone, which compiles the binary and wraps it into a container image. Are you maybe attempting to just build the image using the https://github.com/PrivateBin/Directory/blob/master/Dockerfile only? This doesn't compile anything, but assumes you compiled it somehow else, like running `cargo build` or using a build environment like is done in the Makefile https://github.com/PrivateBin/Directory/blob/c217fe9b858a520862913f8cf158dd22446231b5/Makefile#L27-L32
