### ISSUE TITLE
IPv6 column

### ISSUE THREAD

**Issue by MaxS0niX** [PrivateBin/Directory#25]
Hi! Some of the bins support IPv6, is it possible to add a column for tracking and sorting?)

**Comment by elrido** [comment]
Sorry for the late reply. Personally am very much in favour of IPv6 and been using and advocating it for years. The server hosting it is IPv6 and 4 capable so there would be no technical problem in doing it.

That said, I'm not sure I can see a reason to justify this as something that PrivateBin instances should be nudged into offering, from a privacy or security perspective. Would you be interested in having this purily in the API or displayed on the site as well? @rugk, any second opinions on such a feature? I'm probably a bit biased on this topic...

**Comment by rugk** [comment]
Well, that would be similar to https://ipv6.watch/ or so. But I also hardly see a reason to show this for every user. I mean it does not really matter for an ordinary user and likely only nerds care about this.

Also note its "only" 8 years until IPv4 will die, supposedly: https://ipv4flagday.net/

**Comment by MaxS0niX** [comment]
@elrido @rugk Thanks for answers)

> Would you be interested in having this purily in the API or displayed on the site as well?

As a user of the site, I preferred the display on it.

> I mean it does not really matter for an ordinary user and likely only nerds care about this.

Most likely you are right. I just had to manually watch which bins use ipv6. And by analogy, I liked how https://searx.space/ is used here. I thought this was useful for highlighting the use of IPv6.

I'm glad to hear your opinion on this matter. If it's too labor-intensive, then it probably doesn't make much sense.
