### ISSUE TITLE
Request to Update Instance Location for privatebin.polido.pt

### ISSUE THREAD

**Issue by 7zx** [PrivateBin/Directory#52]
I recently added my PrivateBin instance [privatebin.polido.pt](https://privatebin.polido.pt/) , to the directory on your website, [privatebin.info/directory/](https://privatebin.info/directory/) . I noticed that the directory lists the location of my instance as the USA, likely due to the use of the Cloudflare CDN.

I would like to request a manual update to reflect the accurate location of my instance, which is hosted in Portugal. I understand the importance of accurate geolocation data for users seeking instances closer to their region for improved performance.

To verify my ownership of the domain/instance and to provide the necessary information for the update, I can offer the following details:

1. Domain ownership confirmation.
2. Server hosting location documentation.
3. Any other information required to verify the location.

Please let me know how I can assist in this process, and if any additional information is needed from my end. Ensuring that the location is correctly represented in the directory will be greatly appreciated by both me and potential users of my instance.

**Comment by elrido** [comment]
Any manual intervention would not persist, as the nightly full refresh will always update all the instances. The application isn't designed to allow some data to be skipped during checks, but to automate as much as possible, so we don't have to spend time to manually curate information as we had to with the wiki based predecessor.
